### PR TITLE
LCD-25116 Add example for 5 hosting services

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LCD-25116

### CODE REVIEW

**Comment by tainguyen100** [comment]
@anthony-chu I asked on your Manual test plan too, but does your testing include deploying a sixth service to view the truncation?

**Comment by anthony-chu** [comment]
@christieyoo i did take a look at the 8 services example. i wanted to cover the 5 services case specifically since the default maximum number of services we provide for our customers on any environment is 5 (the services stack, minus CI).

@tainguyen100 i hadn't thought about scenarios greater than 5 services, it might be helpful to cover, but i didn't consider it a priority.

**Comment by tainguyen100** [comment]
@anthony-chu I think it'll be helpful to cover. This one environment being used for the LXC demo has more than 5
image

**Comment by anthony-chu** [comment]
thanks @tainguyen100. i'll go ahead and add that to my tests. i think it'll be sufficient to use the `hosting-8-services` to verify, since we'll be able to see the right count for services.

**Pull request merged**
