### PR TITLE
LCE-6739 add Dockerfile to nodejs service

### PR DESCRIPTION
**Pull request by yijutuan**
This additional dockerfile is needed to change nodejs service to be a recipe type docker.

### CODE REVIEW

**Comment by yijutuan** [comment]
Not sure how testing works for this PR since I created it as a AdHoc API task... 

but here are the proof of the results from deploying these! 

```
{
  "autoscale": {
    "cpu": 80,
    "memory": 80,
    "maxInstances": 10
  },
  "buildGroupUid": 2,
  "canAutoscale": false,
  "cluster": "us-west1-c1",
  "command": [
    "npm",
    "run",
    "start"
  ],
  "constraints": [],
  "cpu": 1,
  "createdAt": 1662070263419,
  "dependencies": [],
  "deployGroupUid": 2,
  "env": null,
  "health": "none",
  "id": "fqmrhxmljwkvunnyxn",
  "image": "gcr.io/liferaycloud-development/yizpe5qmdl47s828p8ksmsf8r:2",
  "imageHint": "node:lts-alpine",
  "kind": "Deployment",
  "livenessProbe": null,
  "loadBalancer": {
    "defaultBackend": false,
    "cdn": false,
    "customDomains": []
  },
  "memory": 1024,
  "podManagementPolicy": "OrderedReady",
  "ports": [],
  "projectId": "rttest-test",
  "projectUid": "rpenkndwlgkuaqbppz",
  "publishNotReadyAddressesForCluster": true,
  "readinessProbe": null,
  "ready": true,
  "readyLastTransitionAt": 1662070266000,
  "recipeType": "dockerfile",
  "scale": 1,
  "serviceId": "nodehog",
  "status": "running",
  "volumes": {},
  "readyValue": "ready",
  "friendlyCreatedAt": "42 seconds ago"
}
```

```
{
  "autoscale": {
    "cpu": 80,
    "memory": 80,
    "maxInstances": 10
  },
  "buildGroupUid": 1,
  "canAutoscale": false,
  "cluster": "us-west1-c1",
  "command": [
    "npm",
    "run",
    "start"
  ],
  "constraints": [],
  "cpu": 1,
  "createdAt": 1662070173337,
  "dependencies": [],
  "deployGroupUid": 1,
  "env": null,
  "health": "none",
  "id": "xpowvxpqdvmnnwgqks",
  "image": "gcr.io/liferaycloud-development/e6shfxqqrjdstiahdialulxlv:1",
  "imageHint": "node:lts-alpine",
  "kind": "Deployment",
  "livenessProbe": null,
  "loadBalancer": {
    "defaultBackend": false,
    "cdn": false,
    "customDomains": []
  },
  "memory": 1024,
  "podManagementPolicy": "OrderedReady",
  "ports": [],
  "projectId": "rttest",
  "projectUid": "omirphouhefvmnvhnt",
  "publishNotReadyAddressesForCluster": true,
  "readinessProbe": null,
  "ready": true,
  "readyLastTransitionAt": 1662070179000,
  "recipeType": "dockerfile",
  "scale": 1,
  "serviceId": "nodehog",
  "status": "running",
  "volumes": {},
  "readyValue": "ready",
  "friendlyCreatedAt": "3 minutes ago"
}
```

Note the recipeTypes are no longer nodejs, but dockerfile.

**Comment by tainguyen100** [comment]
> Not sure how testing works for this PR since I created it as a AdHoc API task...

We normally just review and merge like we do for `lcp-functional-tests`. In this case, since we're updating an existing service, I might run some of the tests which uses `nodehog` and `nodehog-stress-10-destress-0`, but they look fine from the small testing I did with the Dockerfiles, so I don't believe that will be necessary. The results from the deployments you did will suffice.

**Review by tainguyen100 — APPROVED** [review]
Lgtm!

**Review by christieyoo — APPROVED** [review]
Thanks @yijutuan!

I tested deployment with `api:5.38.2-rc1` and `PR-5323_20220901-1836_94622677`. Successful in both cases.

**Review by leandroaguiar-lr — APPROVED** [review]

**Pull request merged**
